baseURL: "https://www.vijay-narayanan.com/"
languageCode: "en-us"
title: "Vijay Narayanan"
theme: "PaperMod"

enableRobotsTXT: true
pagination:
  pagerSize: 10
buildDrafts: false
buildFuture: false
buildExpired: false
canonifyURLs: true

# Disable Google Analytics partial error
params:
  env: "production"  # or "development"
  disableGoogleAnalytics: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowToc: true
  ShowCodeCopyButtons: true
  defaultTheme: "auto"  # auto/light/dark toggle support
  ShowWordCount: true
  ShowLastMod: true
  comments: false

  homeInfoParams:
    Title: "Hi, I'm Vijay 👋"
    Content: "Welcome to my blog. I'm a technologist passionate about DevOps, cloud infrastructure, and automation."

  socialIcons:
    - name: "github"
      url: "https://github.com/vijaynarayanan-it"
    - name: "email"
      url: "mailto:vijaynarayanan.it@gmail.com"

  assets:
    disableHLJS: false

  footer:
    contact: "vijaynarayanan.it@gmail.com"
    location: "Netherlands"
    github: "https://github.com/vijaynarayanan-it"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3
    - identifier: search
      name: Search
      url: /search/
      weight: 4

outputs:
  home:
    - HTML
    - RSS
    - JSON  # Required for search

markup:
  highlight:
    noClasses: false
    style: github-dark
