baseURL = "https://www.vijay-narayanan.com/"
languageCode = "en-us"
title = "Vijay Narayanan"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true
  defaultTheme = "auto"  # Light/dark toggle
  ShowCodeCopyButtons = true

[params.homeInfoParams]
  Title = "Hi, I'm Vijay 👋"
  Content = "Welcome to my blog. I'm a technologist passionate about DevOps, cloud infrastructure, and automation."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/YOUR_USERNAME"

[[params.socialIcons]]
  name = "email"
  url = "mailto:you@example.com"

[params.footer]
  contact = "you@example.com"
  location = "Netherlands"
  github = "https://github.com/YOUR_USERNAME"
